import * as fs from 'fs';
import { parseAndGenerateStateMachineComponents } from '../e2e/base.e2e';

console.log("Generating simulators from generators in " + process.argv[2] + " to " + process.argv[3] + "/generated-simulators");
const filenames = fs.readdirSync(process.argv[2]);

for (const filename of filenames) {
    const generator = fs.readFileSync(process.argv[2] + "/" + filename, 'utf8');

    const { stateMachine } = parseAndGenerateStateMachineComponents(generator);
    const commentedAndExported = "// Generated by npm run generate.simulators\n\nexport " + stateMachine + "\n\nexport " + generator;
    fs.writeFileSync(process.argv[3] + "/generated-simulators/" + filename, commentedAndExported);
}

console.log("Done, generated " + filenames.length + " simulators.");
